apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-html
  namespace: default
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Hello</title></head>
      <body><h1>Hello world</h1></body>
    </html>
